server:
  port: 0
grpc:
  server:
    port: 0
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: aggregator-consumer-group
  jackson:
    time-zone: Europe/Moscow
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
kafka:
  topics:
    user-actions: stats.user-actions.v1
    events-similarity: stats.events-similarity.v1
logging:
  pattern:
    console: "[%X{requestId}] %d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
  level:
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    sun.rmi: INFO
    java.io.serialization: INFO
    org.apache.tomcat.util.net.NioEndpoint: INFO